# fly.toml app configuration file for french-voyage-backend
# Optimized for free-tier usage

app = "french-voyage-backend"
primary_region = "mad"  

[build]
  image = "node:18" 

[env]
  PORT = "3000"  

[http_service]
  internal_port = 3000 
  force_https = true 
  auto_stop_machines = "stop"  
  auto_start_machines = true  
  min_machines_running = 1 
  processes = ["app"]

[[vm]]
  memory = "256mb" 
  cpu_kind = "shared"
  cpus = 1
